#!/bin/bash

set -e;

out="/var/lib/dirsrv/slapd-scripts/ldif/scripts-$(date +%Y_%m_%d_%H_%M_%S).ldif"

dsconf scripts backend export --not-folded -l "$out" dc=scripts,dc=mit,dc=edu > /dev/null

cat "$out"
