all:
  vars:
    scripts_root:
    - username: achernya
    - username: adehnert
      root_mail: adehnert-sipb@mit.edu
    - username: amigdal
    - username: andersk
    - username: btidor
      root_mail: btidor-scripts@mit.edu
    - username: cela
      root_mail: null
    - username: cereslee
    - username: ezyang
    - username: geofft
      root_mail: null
    - username: glasgall
    - username: mitchb
    - username: mrittenb
    - username: quentin
    - username: tboning
    - username: vasilvv
    maintainers: "{{ scripts_root }}"

    scripts_kiddies:
    - username: jnoguera
    - username: rihn

    ip: "{{ lookup('dig', inventory_hostname) | replace('NXDOMAIN', '') }}"

    vips:
    - host: scripts-director.mit.edu
      ip: 18.4.86.132
      cidr_netmask: 24
      nic: vlan486
      type: director
    - host: scripts.mit.edu
      ip: 18.4.86.43
      cidr_netmask: 24
      nic: vlan486
      mail: True
    - host: scripts-cert.mit.edu
      ip: 18.4.86.50
      cidr_netmask: 24
      nic: vlan486
      type: cert
    - host: scripts-vhosts.mit.edu
      ip: 18.4.86.46
      cidr_netmask: 24
      nic: vlan486
      mail: True
    - host: scripts-test.mit.edu
      ip: 18.4.86.229
      cidr_netmask: 24
      nic: vlan486
      codename: Thirty
    - host: sipb.mit.edu
      ip: 18.4.86.29
      cidr_netmask: 24
      nic: vlan486
      type: vhost
    - host: scripts-f20.mit.edu
      ip: 18.4.86.22
      cidr_netmask: 24
      nic: vlan486
      mail: True
      codename: Heisenbug
    - host: scripts-f30.mit.edu
      ip: 18.4.86.30
      cidr_netmask: 24
      nic: vlan486
      mail: True
      codename: Thirty
    
    rsyslogs:
    - 18.4.86.15  # log-flume
    - 18.4.86.16  # log-normal

    mit_dns_servers:
      - 18.0.70.160
      - 18.0.72.3
      - 18.0.71.151

    # Generated from http://kb.mit.edu/confluence/x/F4DCAg + whois, 2019-11-18
    mit_subnets:
      - 10/8
      - 18/11
      - 128.30/15
      - 128.52/16

  children:
    scripts-directors:
      hosts:
        george-lucas.mit.edu:
          vlan486_address: 18.4.86.220
          vlan486_hwaddr: 00:50:56:87:03:c5
        joss-whedon.mit.edu:
          vlan486_address: 18.4.86.226
          vlan486_hwaddr: 00:50:56:87:c2:23
        christopher-nolan.mit.edu:
          vlan486_address: 18.4.86.111
          vlan486_hwaddr: 00:50:56:87:d4:4e

    scripts-proxy:
      vars:
        vlan486_address: "{{ ip }}"
      children:
        scripts-proxy-prod:
          hosts:
            oaken-bucket.mit.edu:
              dscp_tag: 1
            instrumental-variable.mit.edu:
              dscp_tag: 2
            epoxy-resin.mit.edu:
              dscp_tag: 3
        scripts-proxy-test:
          vars:
            maintainers: "{{ scripts_root + scripts_kiddies }}"
          hosts:
            scripts-test-proxy-1.mit.edu:
              dscp_tag: 11
            scripts-test-proxy-2.mit.edu:
              dscp_tag: 12
            scripts-test-proxy-3.mit.edu:
              dscp_tag: 13
        scripts-proxy-quentin:
          vars:
            maintainers:
              - username: quentin
          hosts:
            scripts-test-proxy-quentin-1.mit.edu:

    scripts-syslogs:
      hosts:
        log-flume.mit.edu: {}
        log-normal.mit.edu: {}

    scripts-ldap:
      hosts:
        doppelganger.mit.edu: {}
        alter-ego.mit.edu: {}
        body-double.mit.edu: {}

    sql:
      vars:
        vlan486_address: "{{ ip }}"
        vlan461_address: "{{ ip | replace('18.4.86.', '172.21.0.') | replace('18.4.60.', '172.21.0.') }}"
      hosts:
        sql.mit.edu: {}
        primary-key.mit.edu: {}
        foreign-key.mit.edu: {}
        sliced-bread.mit.edu: {}
      children:
        sql-bullseye:
          hosts:
            multivalue-key.mit.edu:
              vlan486_hwaddr: 00:50:56:87:36:df
              vlan461_hwaddr: 00:50:56:87:7e:48
            unique-key.mit.edu:
              vlan486_hwaddr: 00:50:56:87:22:9e
              vlan461_hwaddr: 00:50:56:87:28:7d

    scripts-real:
      children:
        scripts-real-prod:
          vars:
            vlan486_address: "{{ ip }}"
            vlan461_address: "{{ vlan486_address | replace('18.4.86.', '172.21.0.') }}"
          children:
            scripts-real-f30:
              vars:
                codename: Thirty
              hosts:
                better-mousetrap.mit.edu:
                  vlan486_hwaddr: 00:50:56:87:16:56
                  vlan461_hwaddr: 00:50:56:87:2f:6f
                  primary: True
                old-faithful.mit.edu:
                  vlan486_hwaddr: 00:50:56:87:15:39
                  vlan461_hwaddr: 00:50:56:87:f2:50
                whole-enchilada.mit.edu:
                  vlan486_hwaddr: 00:50:56:87:f5:00
                  vlan461_hwaddr: 00:50:56:87:48:9f
                real-mccoy.mit.edu:
                  vlan486_hwaddr: 00:50:56:87:34:e4
                  vlan461_hwaddr: 00:50:56:87:b6:8b
                golden-egg.mit.edu:
                  vlan486_hwaddr: 00:50:56:87:69:dc
                  vlan461_hwaddr: 00:50:56:87:ba:12
                miracle-cure.mit.edu:
                  vlan486_hwaddr: 00:50:56:87:72:c6
                  vlan461_hwaddr: 00:50:56:87:77:32
                #lucky-star.mit.edu:
            scripts-real-f20:
              vars:
                codename: Heisenbug
              hosts:
                bees-knees.mit.edu:
                cats-whiskers.mit.edu:
                  primary: True
                pancake-bunny.mit.edu:
                busy-beaver.mit.edu:
                shining-armor.mit.edu:
        scripts-real-test:
          vars:
            vips:
              - host: scripts-test.mit.edu
                ip: 18.4.86.229
                cidr_netmask: 24
            enable_testing_repo: yes
            # Don't Zephyr from dev servers
            syslog_client: no
            afs_cache_size: 500000
            use_local_ldap: no
          hosts:
            quentin-ansible-test.xvm.mit.edu: {}

            scripts-f30-test.xvm.mit.edu: {}

            feral-purrbeast.xvm.mit.edu:
              maintainers:
                - username: cela
            poisonous-stamp.xvm.mit.edu:
              maintainers:
                - username: bpchen
            toasted-microwave.xvm.mit.edu:
              maintainers:
                - username: rihn
            miriamscripts.xvm.mit.edu:
              maintainers:
                - username: mrittenb
            anarchyscripts.xvm.mit.edu:
              maintainers:
                - username: jnoguera
