all:
  vars:
    maintainers:
    - username: wmoses
    - username: quentin
    - username: kyeb
    - username: mitimmy

    ip: "{{ lookup('dig', inventory_hostname) | replace('NXDOMAIN', '') }}"

    mit_dns_servers:
      - 18.0.70.160
      - 18.0.72.3
      - 18.0.71.151

  children:
    jupyter:
      hosts:
        jupyter.mit.edu:
