---
- name: Install jupyterhub dependencies
  package:
    name:
      - virtualenv
      - npm
      - nodejs
- name: Install jupyterhub
  pip:
    name:
      jupyterhub
    virtualenv: /opt/jupyterhub
