---
- name: Install jupyterhub dependencies
  package:
    name:
      - virtualenv
      - npm
      - nodejs
      - cython3
      - libhesiod-dev
- npm:
    name: configurable-http-proxy
    global: yes
- name: Install jupyterhub
  pip:
    name:
    - jupyterhub
    - notebook
    - Cython
    - git+https://github.com/macathena/python-hesiod@python3
    - git+https://github.com/macathena/python-afs@py3-debian
    virtualenv: /opt/jupyterhub
