---
- name: Install jupyterhub dependencies
  package:
    name:
      - virtualenv
      - npm
      - nodejs
      - cython3
      - libhesiod-dev
      # User packages
      - python3-gmpy2
      - python3-pyodbc
      - python3-gdal
      - texlive-full
- npm:
    name: configurable-http-proxy
    global: yes
- name: Install jupyterhub
  pip:
    name:
    - jupyterhub
    - jupyterlab
    - jupyterlab_server
    - notebook
    - Cython
    - gssapi
    - oauthenticator
    - git+https://github.com/macathena/python-hesiod@python3
    - git+https://github.com/macathena/python-afs@py3-debian
    # Extra Jupyter features
    - widgetsnbextension
    - ipywidgets
    - jupyter-archive
    - jupyterlab-git
    - jupyterlab-widgets
    - jupyterlab-quickopen
    - jupyterlab-apod
    - jupyterlab-python-file
    - jupyterlab-hdf
    - jupyterlab-latex
    - jupyterlab-kernelspy
    - astrowidgets
    # User packages
    # Inspired by Anaconda package list:
    # curl https://repo.anaconda.com/pkgs/main/linux-64/repodata.json | jq '.packages[.packages | keys | map(select(startswith("_anaconda_depends-20")))[-1]].depends'
    - git+https://github.com/usgs/geomag-algorithms.git
    - argh
    - asn1crypto
    - astroid
    - astroplan
    - astropy
    - atomicwrites
    - attrs
    - autopep8
    - babel
    - backcall
    - beautifulsoup4
    - biopython
    - bitarray
    - bkcharts
    - bleach
    - blosc
    - bokeh
    - boto
    - bottleneck
    - brotlipy
    - cffi
    - chardet
    - click
    - cloudpickle
    - clyent
    - colorama
    - contextlib2
    - cryptography
    - cycler
    - cytoolz
    - dask
    - decorator
    - defusedxml
    - diff-match-patch
    - docutils
    - entrypoints
    - et_xmlfile
    - fastcache
    - filelock
    - flake8
    - flask
    - fsspec
    - future
    - gevent
    - glob2
    - gmpy2
    - greenlet
    - h5py
    - heapdict
    - html5lib
    - icu
    - idna
    - imageio
    - imagesize
    - importlib-metadata
    - intel-openmp
    - intervaltree
    - ipython_genutils
    - isort
    - itsdangerous
    - jdcal
    - jinja2
    - joblib
    - json5
    - jsonschema
    - keyring
    - kiwisolver
    - lazy-object-proxy
    - libarchive-c
    - lief
    - llvmlite
    - locket
    - lxml
    - lz4
    - markupsafe
    - matplotlib
    - mccabe
    - mistune
    - mkl
    - mock
    - more-itertools
    - mpmath
    - msgpack
    - multipledispatch
    - networkx
    - nltk
    - nose
    - notebook
    - numba
    - numexpr
    - numpy
    - olefile
    - openpyxl
    - packaging
    - pandas
    - pandoc
    - pandocfilters
    - parso
    - partd
    - path
    - pathlib2
    - pathtools
    - patsy
    - pep8
    - pexpect
    - pickleshare
    - pillow
    - pkginfo
    - pluggy
    - ply
    - prometheus_client
    - prompt-toolkit
    - psutil
    - ptyprocess
    - py
    - pycodestyle
    - pycosat
    - pycparser
    - pycurl
    - pydocstyle
    - pyflakes
    - pygments
    - pylint
    - pyodbc
    - pyopenssl
    - pyparsing
    - pyrsistent
    - pysocks
    - pytest
    - python-jsonrpc-server
    - python-language-server
    - pytz
    - pywavelets
    - pyxdg
    - pyyaml
    - pyzmq
    - regex
    - requests
    - rope
    - ruamel_yaml
    - scikit-bio
    - scikit-image
    - scikit-learn
    - scikit-rf
    - scikit-dataaccess
    - scipy
    - seaborn
    - secretstorage
    - simplegeneric
    - singledispatch
    - sip
    - six
    - snappy
    - snowballstemmer
    - sortedcollections
    - sortedcontainers
    - soupsieve
    - sqlalchemy
    - statsmodels
    - sympy
    - tables
    - tbb
    - tblib
    - terminado
    - testpath
    - threadpoolctl
    - toml
    - toolz
    - tqdm
    - typing_extensions
    - ujson
    - unicodecsv
    - urllib3
    - watchdog
    - wcwidth
    - webencodings
    - werkzeug
    - wrapt
    - wurlitzer
    - xlrd
    - xlsxwriter
    - xlwt
    - yapf
    - zict
    - zipp
    - zope
    - zope.event
    - zope.interface
    - zstd
    virtualenv: /opt/jupyterhub
    virtualenv_site_packages: yes
- name: Install JupyterLab extensions
  shell: |
    . /opt/jupyterhub/bin/activate
    jupyter labextension check {{extensions|join(" ")}} && exit 37
    jupyter labextension install {{extensions|join(" ")}}
  vars:
    extensions:
    - "@jupyter-widgets/jupyterlab-manager"
    - "@bokeh/jupyter_bokeh"
    - jupyterlab-python-file
    - "@parente/jupyterlab-quickopen"
    - "@jupyterlab/hdf5"
    - "@jupyterlab/latex"
    - jupyterlab-kernelspy
    - jupyterlab-drawio
    - "@aquirdturtle/collapsible_headings"
    - "@jupyterlab/geojson-extension"
  register: result
  changed_when: result.rc != 37
  failed_when: result.rc not in (0, 37)
# TODO: Real database
# TODO: Other config settings
- name: Configure jupyterhub
  copy:
    dest: /opt/jupyterhub/{{item}}
    src: "{{ item }}"
  loop:
    - jupyterhub_config.py
    - register.sh
  notify: restart jupyterhub
- name: Install Python modules
  copy:
    dest: /opt/jupyterhub/lib/python3.8/site-packages/{{item}}
    src: "{{ item }}"
  loop:
    - ccache.py
  notify: restart jupyterhub
- name: Install templates
  copy:
    dest: /opt/jupyterhub
    src: templates
- name: Install JavaScript dependencies
  block:
  - file:
      path: /opt/jupyterhub/static/login
      state: directory
  - copy:
      dest: /opt/jupyterhub/static/login/sjcl.js
      src: webathena/app/scripts/sjcl.js
  - copy:
      dest: /opt/jupyterhub/static/login/
      src: webathena/dist/
- name: Install service
  copy:
    dest: /etc/systemd/system/jupyterhub.service
    src: jupyterhub.service
  notify: restart jupyterhub
  register: unit
- name: Enable service
  service:
    name: jupyterhub
    daemon_reload: "{{ unit.changed }}"
    enabled: yes
