---
- name: Install jupyterhub dependencies
  package:
    name:
      - virtualenv
      - npm
      - nodejs
      - cython3
      - libhesiod-dev
- npm:
    name: configurable-http-proxy
    global: yes
- name: Install jupyterhub
  pip:
    name:
    - jupyterhub
    - notebook
    - Cython
    - gssapi
    - git+https://github.com/macathena/python-hesiod@python3
    - git+https://github.com/macathena/python-afs@py3-debian
    # User packages
    - numpy
    - astropy
    - astroplan
    - pyyaml
    - matplotlib
    - scipy
    virtualenv: /opt/jupyterhub
# TODO: Real database
# TODO: Other config settings
- name: Configure jupyterhub
  copy:
    dest: /opt/jupyterhub/{{item}}
    src: "{{ item }}"
  loop:
    - jupyterhub_config.py
    - register.sh
  notify: restart jupyterhub
- name: Install Python modules
  copy:
    dest: /opt/jupyterhub/lib/python3.8/site-packages/{{item}}
    src: "{{ item }}"
  loop:
    - ccache.py
  notify: restart jupyterhub
- name: Install templates
  copy:
    dest: /opt/jupyterhub
    src: templates
- name: Install service
  copy:
    dest: /etc/systemd/system/jupyterhub.service
    src: jupyterhub.service
  notify: restart jupyterhub
  register: unit
- name: Enable service
  service:
    name: jupyterhub
    daemon_reload: "{{ unit.changed }}"
    enabled: yes
