---
- name: Install jupyterhub dependencies
  package:
    name:
      - virtualenv
      - npm
      - nodejs
- npm:
    name: configurable-http-proxy
    global: yes
- name: Install jupyterhub
  pip:
    name:
      jupyterhub
    virtualenv: /opt/jupyterhub
