#!/bin/sh

# This script renews afsagent's tickets and tokens.
# It is called by systemd on a regular schedule.

export KRB5CCNAME=/home/afsagent/krb5cc
export KRBTKFILE=/home/afsagent/tkt

princ="$(/usr/bin/klist -k /etc/daemon.keytab | awk 'NR == 4 { print $2 }')"

# Option #1: invoke kinit with a password
#echo "password" | /usr/bin/kinit >/dev/null "$princ"

# Option #2: invoke kinit with a keytab
/usr/bin/kinit -k -t /etc/daemon.keytab "$princ"

# Obtain AFS tokens
aklog
aklog -c sipb
aklog -c csail
