#!/bin/sh
(
    echo "Ignoring request from kernel: modprobe $*"
    stacks=$(grep -ls request_module /proc/*/stack)
    if [ "$stacks" ]; then
	ps -Lfwp $(for stack in $stacks; do
		proc="${stack%/stack}"
		echo "${proc#/proc/}";
	    done)
    fi
) | logger -p authpriv.info
false
