/usr/bin/cgexec:install:chmod ug-s /usr/bin/cgexec
/usr/bin/fusermount:install:chmod ug-s /usr/bin/fusermount
/usr/bin/mount:install:chmod ug-s /usr/bin/mount
/usr/bin/su:install:chmod ug-s /usr/bin/su
/usr/bin/umount:install:chmod ug-s /usr/bin/umount
/usr/sbin/mount.nfs:install:chmod ug-s /usr/sbin/mount.nfs
/usr/sbin/netreport:install:chmod ug-s /usr/sbin/netreport
/usr/bin/chage:install:chmod ug-s /usr/bin/chage
/usr/bin/chfn:install:chmod ug-s /usr/bin/chfn
/usr/bin/chsh:install:chmod ug-s /usr/bin/chsh
/usr/bin/gpasswd:install:chmod ug-s /usr/bin/gpasswd
/usr/bin/lockfile:install:chmod ug-s /usr/bin/lockfile
/usr/bin/newgrp:install:chmod ug-s /usr/bin/newgrp
/usr/bin/newrole:install:chmod ug-s /usr/bin/newrole
/usr/bin/passwd:install:chmod ug-s /usr/bin/passwd
/usr/bin/rcp:install:chmod ug-s /usr/bin/rcp
/usr/bin/rlogin:install:chmod ug-s /usr/bin/rlogin
/usr/bin/rsh:install:chmod ug-s /usr/bin/rsh
/usr/bin/sperl5.10.1:install:chmod ug-s /usr/bin/sperl5.10.1
/usr/bin/ssh-agent:install:chmod ug-s /usr/bin/ssh-agent
/usr/bin/wall:install:chmod ug-s /usr/bin/wall
/usr/bin/write:install:chmod ug-s /usr/bin/write
/usr/bin/Xorg:install:chmod ug-s /usr/bin/Xorg
/usr/bin/ksu:install:chmod ug-s /usr/bin/ksu
/usr/lib64/nspluginwrapper/plugin-config:install:chmod ug-s /usr/lib64/nspluginwrapper/plugin-config
/usr/lib64/vte/gnome-pty-helper:install:chmod ug-s /usr/lib64/vte/gnome-pty-helper
/usr/libexec/kde4/kpac_dhcp_helper:install:chmod ug-s /usr/libexec/kde4/kpac_dhcp_helper
/usr/sbin/ccreds_chkpwd:install:chmod ug-s /usr/sbin/ccreds_chkpwd
/usr/sbin/userisdnctl:install:chmod ug-s /usr/sbin/userisdnctl
/usr/sbin/usernetctl:install:chmod ug-s /usr/sbin/usernetctl
/usr/bin/pkexec:install:chmod ug-s /usr/bin/pkexec
